# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfa386afd0b38807dc06a7ab9bf956105ec2257eb69ac2a2c976682822b4309ce0b9aae02562b6bd8e90a38a391d464bc107718a5eb815b2319dec8ef372081c

test:
  secret_key_base: 55e7a0974561ab80f71967f77976b2c92c7189e55300e4b557fa15a1d356a30f8c96bc305dfbefa55e7ad8ffeb2863e6f1457da03453485877d382d456268a7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
